# Generated by Django 5.2 on 2025-04-21 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sms_number', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_holder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=128)),
                ('frequency', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('prescriber', models.CharField(max_length=255)),
                ('medication_regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='reminders.medicationregime')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sms_number', models.CharField(blank=True, max_length=32)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_users', to='reminders.accountholder')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('sms', 'SMS'), ('voice_call', 'Voice Call'), ('email', 'Email')], max_length=16)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('media_record', models.FileField(blank=True, null=True, upload_to='session_media/')),
                ('outcome_notes', models.TextField(blank=True)),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reminders.serviceuser')),
            ],
        ),
        migrations.AddField(
            model_name='medicationregime',
            name='service_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_regimes', to='reminders.serviceuser'),
        ),
    ]
