# Generated by Django 5.2 on 2025-04-21 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel("ServiceUser", "CircleMember"),
        migrations.RenameField("medicationregime", "service_user", "circle_member"),
        migrations.RenameField("servicesession", "service_user", "circle_member"),
    ]
