# Generated by Django 5.2 on 2025-04-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20250421_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationregime',
            name='natural_language_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='circlemember',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_members', to='reminders.accountholder'),
        ),
    ]
