# Generated by Cascade AI: Add prescriptions_description to CircleMember
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0003_medicationregime_natural_language_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circlemember",
            name="prescriptions_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
