# Generated by Cascade AI: Move Prescription to CircleMember, remove medication_regime FK
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0004_circlemember_prescriptions_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="circle_member",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="prescriptions", to="reminders.circlemember"),
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medication_regime",
        ),
        migrations.AlterField(
            model_name="prescription",
            name="circle_member",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prescriptions", to="reminders.circlemember"),
        ),
    ]
