# Generated by Django 5.2 on 2025-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_prescription_circle_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescriber',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
