# Generated by Django 5.2 on 2025-04-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_alter_prescription_prescriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='time_of_day',
            field=models.CharField(blank=True, help_text="Optional time of day for taking medication, e.g., '08:00' or 'morning'.", max_length=32),
        ),
    ]
